#ifndef APP_ALARM_CONFIG_H
#define APP_ALARM_CONFIG_H

#define ALARM_TEMP_HIGH_THRESHOLD   30.0f
#define ALARM_TEMP_LOW_THRESHOLD     5.0f
#define ALARM_HUMI_HIGH_THRESHOLD   80.0f
#define ALARM_HUMI_LOW_THRESHOLD    20.0f
#define ALARM_CO2_HIGH_THRESHOLD    1000U
#define ALARM_LIGHT_HIGH_THRESHOLD  2000U
#define ALARM_LIGHT_LOW_THRESHOLD     50U
#define ALARM_VIN_LOW_THRESHOLD     10.5f
#define ALARM_AIN1_HIGH_THRESHOLD    3.0f
#define ALARM_AIN2_HIGH_THRESHOLD    3.0f

#endif /* APP_ALARM_CONFIG_H */
